ALTER TABLE agent_task_queue ADD COLUMN IF NOT EXISTS execution_id UUID;
ALTER TABLE task_token ADD COLUMN IF NOT EXISTS execution_id UUID;
ALTER TABLE external_pull_request_link
    ADD COLUMN IF NOT EXISTS target_instance TEXT,
    ADD COLUMN IF NOT EXISTS canonical_repository_id TEXT,
    ADD COLUMN IF NOT EXISTS canonical_repository TEXT,
    ADD COLUMN IF NOT EXISTS provider_binding_id TEXT,
    ADD COLUMN IF NOT EXISTS provider_binding_revision TEXT,
    ADD COLUMN IF NOT EXISTS provider_repository TEXT,
    ADD COLUMN IF NOT EXISTS expected_head_sha TEXT,
    ADD COLUMN IF NOT EXISTS expected_base_sha TEXT,
    ADD COLUMN IF NOT EXISTS base_ref TEXT,
    ADD COLUMN IF NOT EXISTS delegated_merge_method TEXT,
    ADD COLUMN IF NOT EXISTS projection_facts_revision TEXT;

CREATE TABLE IF NOT EXISTS workload_pr_merge_delegation (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL,
    issue_id UUID NOT NULL,
    external_pr_link_id UUID NOT NULL,
    task_id UUID NOT NULL,
    execution_id UUID NOT NULL,
    runtime_id UUID NOT NULL,
    operation TEXT NOT NULL DEFAULT 'pr.merge' CHECK (operation = 'pr.merge'),
    target_instance TEXT NOT NULL CHECK (target_instance ~ '^[a-z0-9][a-z0-9.-]{0,63}$'),
    canonical_repository_id TEXT NOT NULL CHECK (canonical_repository_id ~ '^sha256:[a-f0-9]{64}$'),
    canonical_repository TEXT NOT NULL CHECK (canonical_repository ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,99}/[A-Za-z0-9][A-Za-z0-9._-]{0,99}$'),
    provider TEXT NOT NULL DEFAULT 'forgejo' CHECK (provider = 'forgejo'),
    provider_binding_id TEXT NOT NULL CHECK (provider_binding_id ~ '^sha256:[a-f0-9]{64}$'),
    provider_binding_revision TEXT NOT NULL CHECK (provider_binding_revision ~ '^sha256:[a-f0-9]{64}$'),
    provider_repository TEXT NOT NULL CHECK (provider_repository ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,99}/[A-Za-z0-9][A-Za-z0-9._-]{0,99}$'),
    ags_pr_number BIGINT NOT NULL CHECK (ags_pr_number > 0),
    provider_pr_number BIGINT NOT NULL CHECK (provider_pr_number > 0),
    expected_head_sha TEXT NOT NULL CHECK (expected_head_sha ~ '^[a-f0-9]{40}$'),
    expected_base_sha TEXT NOT NULL CHECK (expected_base_sha ~ '^[a-f0-9]{40}$'),
    base_ref TEXT NOT NULL CHECK (base_ref = btrim(base_ref) AND base_ref <> ''),
    merge_method TEXT NOT NULL CHECK (merge_method IN ('merge', 'rebase', 'rebase-merge', 'squash', 'fast-forward-only')),
    projection_facts_revision TEXT NOT NULL CHECK (projection_facts_revision ~ '^sha256:[a-f0-9]{64}$'),
    facts_digest TEXT NOT NULL CHECK (facts_digest ~ '^sha256:[a-f0-9]{64}$'),
    authority_revision UUID NOT NULL DEFAULT gen_random_uuid(),
    approval_policy_revision TEXT NOT NULL DEFAULT 'workload.pr-merge-approval.v2',
    state TEXT NOT NULL CHECK (state IN ('pending_approval', 'approved', 'consumed', 'revoked', 'expired', 'superseded')),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_at TIMESTAMPTZ,
    approved_by_user_id UUID,
    not_after TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_by_user_id UUID,
    revocation_reason TEXT,
    superseded_at TIMESTAMPTZ,
    supersede_reason TEXT,
    consumer_instance_id TEXT,
    consumer_intent_id UUID,
    consume_request_digest TEXT,
    consumption_receipt_id UUID,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((state = 'pending_approval' AND approved_at IS NULL AND approved_by_user_id IS NULL AND not_after IS NULL) OR state <> 'pending_approval'),
    CHECK ((state IN ('approved', 'consumed') AND approved_at IS NOT NULL AND approved_by_user_id IS NOT NULL AND not_after IS NOT NULL) OR state NOT IN ('approved', 'consumed')),
    CHECK ((state = 'consumed' AND consumer_instance_id IS NOT NULL AND consumer_intent_id IS NOT NULL AND consume_request_digest IS NOT NULL AND consumption_receipt_id IS NOT NULL AND consumed_at IS NOT NULL) OR state <> 'consumed'),
    CHECK ((state = 'revoked' AND revoked_at IS NOT NULL AND revoked_by_user_id IS NOT NULL AND revocation_reason IS NOT NULL AND revocation_reason <> '') OR state <> 'revoked'),
    CHECK ((state = 'superseded' AND superseded_at IS NOT NULL AND supersede_reason IS NOT NULL AND supersede_reason <> '') OR state <> 'superseded')
);

CREATE TABLE IF NOT EXISTS workload_pr_merge_delegation_event (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL,
    issue_id UUID NOT NULL,
    delegation_id UUID NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('request_created', 'approved', 'revoked', 'expired', 'superseded', 'consumed', 'effect_confirmed', 'effect_outcome_unknown')),
    actor_type TEXT NOT NULL CHECK (actor_type IN ('human', 'task', 'ags_service', 'system')),
    actor_id TEXT NOT NULL CHECK (actor_id = btrim(actor_id) AND actor_id <> ''),
    consumer_intent_id UUID,
    details JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(details) = 'object'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
